name: nokdkk

dependencies:
  - conda=4.13.0
  - pip=21.1.2
  - python=3.7.2
  - pip:
    - yahoofinancials==1.6
    - yfinance==0.1.72
    - numpy==1.21.6
    - pandas==1.3.5
    - pyyaml==6.0
    - scikit-learn==1.0.2
    - matplotlib==3.5.2
    - statsmodels==0.13.2
    - seaborn==0.11.2
    - munch==2.5.0
    - fire==0.4.0
    - tqdm==4.64.0
    - catboost==1.0.6
    - -e .